#多环境配置
spring:
  profiles:
    active: dev
---
#--------------------------------------------------通用配置开始-------------------------------------------------#
jwt:
  header: Authorization
  secret: 127.0.0.1
  expiration: 60
  criticalTime: 648000
spring:
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
      ddl-auto: update #生产环境慎用update create
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect  #不加这句则默认为myisam引擎
duanwj:
  value: ${random.value} # 随机字符串
  int: ${random.int} # 随机int
# 暴露所有监控的接口
management:
  endpoints:
    web:
      exposure:
        include: "*"
        exclude: env,beans
# 监控管理界面登陆用户名和密码
security:
  user: admin
  password: admin

#--------------------------------------------------通用配置结束-------------------------------------------------#
---
spring:
  profiles: dev
  datasource:
    primary:
      jdbc-url: jdbc:mysql://127.0.0.1:3306/primary?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false
      driver-class-name: com.mysql.jdbc.Driver
      username: root
      password: 123456
    secondary:
      jdbc-url: jdbc:mysql://127.0.0.1:3306/secondary?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false
      driver-class-name: com.mysql.jdbc.Driver
      username: root
      password: 123456
server:
   port: 8080
---
spring:
  profiles: test
  datasource:
    primary:
      jdbc-url: jdbc:mysql://127.0.0.1:3306/primary?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false
      driver-class-name: com.mysql.jdbc.Driver
      username: root
      password: 123456
    secondary:
      jdbc-url: jdbc:mysql://127.0.0.1:3306/secondary?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false
      driver-class-name: com.mysql.jdbc.Driver
      username: root
      password: 123456
server:
  port: 8081
---
spring:
  profiles: prd
  datasource:
    primary:
      jdbc-url: jdbc:mysql://127.0.0.1:3306/primary?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false
      driver-class-name: com.mysql.jdbc.Driver
      username: root
      password: 123456
    secondary:
      jdbc-url: jdbc:mysql://127.0.0.1:3306/secondary?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false
      driver-class-name: com.mysql.jdbc.Driver
      username: root
      password: 123456
server:
  port: 80